// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:68a814b0-55ef-4d67-be2c-e1f4ec1d75a9',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'notes-hosting-mobilehub-1849362732',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1rml10tf9ri89.cloudfront.net',
    'aws_mobile_analytics_app_id': 'd98a46dcd284415498b935ff62bea457',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '4751d7a5-f2d8-485c-a6a8-8deb2dfa1a13',
    'aws_project_name': 'notes',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'notes-mobilehub-1849362732',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_KYHJKb1SR',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2vpo9edvnc3jig5uiu2u8qcpe',
}

export default awsmobile;
